# -*- coding: utf-8 -*-
"""samplingass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_h8-yEa854rUI904XOhmkSbgidy3LNI
"""

pip install pandas numpy matplotlib seaborn scikit-learn imbalanced-learn

import pandas as pd

df = pd.read_csv('/content/Creditcard_data.csv')
print(df.head())
print(df['Class'].value_counts())

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x=df['Class'])
plt.title("Class Distribution Before Balancing")
plt.show()

from imblearn.over_sampling import SMOTE

X = df.drop('Class', axis=1)
y = df['Class']

smote = SMOTE(random_state=42)
X_bal, y_bal = smote.fit_resample(X, y)

print(pd.Series(y_bal).value_counts())

from sklearn.model_selection import train_test_split

samples = []
for i in range(5):
    X_train, X_test, y_train, y_test = train_test_split(
        X_bal, y_bal, test_size=0.3, random_state=i
    )
    samples.append((X_train, X_test, y_train, y_test))

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

models = {
    "M1": LogisticRegression(max_iter=1000),
    "M2": DecisionTreeClassifier(),
    "M3": RandomForestClassifier(n_estimators=50),
    "M4": SVC(),
    "M5": GaussianNB()
}

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_bal_scaled = scaler.fit_transform(X_bal)

from imblearn.under_sampling import RandomUnderSampler, NearMiss, ClusterCentroids
from imblearn.over_sampling import RandomOverSampler

techniques = {
    "Sampling1": RandomUnderSampler(),
    "Sampling2": RandomOverSampler(),
    "Sampling3": SMOTE(),
    "Sampling4": NearMiss(),
    "Sampling5": ClusterCentroids()
}

from sklearn.linear_model import LogisticRegression

models = {
    "M1": LogisticRegression(max_iter=500, solver='lbfgs'),
    "M2": DecisionTreeClassifier(),
    "M3": RandomForestClassifier(n_estimators=50),
    "M4": SVC(),
    "M5": GaussianNB()
}

from sklearn.metrics import accuracy_score

results = {}

for s_name, sampler in techniques.items():
    results[s_name] = {}

    for m_name, model in models.items():
        X_res, y_res = sampler.fit_resample(X_bal, y_bal)
        X_train, X_test, y_train, y_test = train_test_split(
            X_res, y_res, test_size=0.3, random_state=42
        )

        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)

        results[s_name][m_name] = round(acc * 100, 2)

print(pd.DataFrame(results))

"""“During experimentation, a convergence warning was observed for Logistic Regression. To resolve this, the dataset was standardized using StandardScaler and the maximum number of iterations was increased to 500. After scaling, the models converged properly and produced stable, reliable accuracy scores. The results demonstrate that different sampling techniques perform differently across machine learning models, confirming that no single sampling method is universally optimal.”"""